# Generated by Django 3.0.8 on 2020-08-17 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fcast',
            fields=[
                ('utc_timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('dishwasher', models.FloatField(max_length=40)),
                ('electric_vehicle', models.FloatField(max_length=40)),
                ('freezer', models.FloatField(max_length=40)),
                ('grid_export', models.FloatField(max_length=40)),
                ('grid_import', models.FloatField(max_length=40)),
                ('heat_pump', models.FloatField(max_length=40)),
                ('pv', models.FloatField(max_length=40)),
                ('refrigerator', models.FloatField(max_length=40)),
                ('washing_machine', models.FloatField(max_length=40)),
                ('total_load_consume', models.FloatField(max_length=40)),
                ('daily_avg', models.FloatField(max_length=40)),
            ],
        ),
    ]
